"""Outcome Contract — formal definition of mission success (ADR-053).

Generated by LLM at mission start, validated by Pydantic, consumed by:
- WorkflowCompiler (decides what to plan)
- PlanCritic (validates plan covers contract)
- SemanticVerifier (checks deliverables against success criteria)
- MissionSupervisor (decides when mission is actually done)

Contract generation failures degrade gracefully: a minimal default contract
is always produced so the mission never hard-fails at this stage.
"""
import json
import os
import re
from datetime import datetime
from typing import Any, Dict, List, Optional

from pydantic import BaseModel

from packages.core.models import MissionIntent


class OutcomeContract(BaseModel):
    objective: str
    success_criteria: List[str] = []
    required_deliverables: List[str] = []
    required_evidence: List[str] = []
    constraints: List[str] = []
    deadline: Optional[datetime] = None
    approval_policy: str = "default"   # default | strict | autonomous
    needs_external_research: bool = False

    def to_human_summary(self) -> str:
        lines = [f"Objective: {self.objective}"]
        if self.required_deliverables:
            lines.append("Deliverables:")
            lines.extend(f"  • {d}" for d in self.required_deliverables)
        if self.required_evidence:
            lines.append("Required evidence:")
            lines.extend(f"  • {e}" for e in self.required_evidence)
        if self.constraints:
            lines.append("Constraints:")
            lines.extend(f"  • {c}" for c in self.constraints)
        return "\n".join(lines)


CONTRACT_PROMPT = """You are NEXORA's Outcome Contract generator.
Given a user goal, produce a JSON contract that formally defines what success looks like.

USER GOAL:
{goal}

Return ONLY valid JSON matching this schema:
{{
  "objective": "one sentence restatement of the goal",
  "success_criteria": ["list of verifiable conditions for success"],
  "required_deliverables": ["concrete artifacts/documents/outputs to produce"],
  "required_evidence": ["information or sources needed to produce the deliverables"],
  "constraints": ["boundaries, prohibitions, or requirements"],
  "needs_external_research": true|false
}}

Rules:
- Be concrete, not vague.
- Deliverables should be specific (e.g. "financial model spreadsheet" not "financial analysis").
- If the goal requires information outside the user's own files (market data, competitors, external facts), set needs_external_research to true.
- For travel, recommendation, or creative goals, include exactly ONE visual
  deliverable, phrased in the singular and satisfiable by a single generated
  image (e.g. "a hero inspiration image"). Never ask for "a set", "a series",
  "a collection", or "images" (plural) — one image is what gets produced.
- Every success_criterion must be checkable against the deliverables you listed.
  Do not require a quantity or format the listed deliverables cannot show.
- Do NOT include tool names (no "google docs", no "veo"). Describe outcomes, not tools.
- SCOPE THE AMBITION TO THE GOAL. If the user says "short", "quick", "brief",
  "just", or asks for a single thing, return exactly 1-2 deliverables. Only a
  goal that explicitly asks to "prepare everything" / lists multiple artifacts
  should get 4+ deliverables. Never pad.
- Do NOT split one deliverable into sub-parts. A "study plan" is ONE document,
  not a roadmap doc + a schedule doc + a self-assessment doc. Merge related
  outputs into a single deliverable unless the goal explicitly asks for them
  as separate files.
- Keep it concise: 1-6 deliverables, 2-5 success criteria, 1-4 evidence items.
"""


DEFAULT_CONTRACT = {
    "objective": "Execute the requested goal.",
    "success_criteria": ["The requested work is completed."],
    "required_deliverables": ["Summary of completed work"],
    "required_evidence": [],
    "constraints": ["No external communication without approval"],
    "needs_external_research": False,
}


class ContractGenerator:
    """LLM-based contract generator with deterministic fallback."""

    def __init__(self, api_key: Optional[str] = None, model: Optional[str] = None,
                 call_fn=None):
        self.api_key = api_key if api_key is not None else os.getenv("GEMINI_API_KEY", "")
        self.model = model or os.getenv("NEXORA_MODEL_T2", "gemini-3.5-flash")
        self.call_fn = call_fn   # test seam

    async def generate(self, goal: str, intent: Optional[MissionIntent] = None) -> OutcomeContract:
        from nexora.core.llm_client import llm_available
        if not self.call_fn and not llm_available():
            return self._minimal_contract(goal)

        try:
            text = await self._call(self._prompt(goal))
            parsed = self._parse(text)
            if parsed is None:
                return self._minimal_contract(goal)
            return OutcomeContract(**parsed)
        except Exception:
            # Graceful degradation — never hard-fail a mission at contract stage
            return self._minimal_contract(goal)

    async def _call(self, prompt: str) -> str:
        if self.call_fn:
            return self.call_fn(prompt)
        from nexora.core.adk_runtime import try_run_agent
        adk = await try_run_agent(
            role="Mission Architect",
            instruction=("You are NEXORA's Mission Architect. You turn a goal into a "
                         "formal, checkable Outcome Contract. You output only JSON."),
            task=prompt)
        if adk and adk.strip():
            return adk
        from nexora.core.llm_client import llm_generate
        return await llm_generate(prompt, temperature=0.2, model=self.model)

    def _prompt(self, goal: str) -> str:
        return CONTRACT_PROMPT.format(goal=goal)

    def _parse(self, text: str) -> Optional[Dict[str, Any]]:
        m = re.search(r"\{.*\}", text, re.S)
        if not m:
            return None
        try:
            return json.loads(m.group(0))
        except Exception:
            return None

    def _minimal_contract(self, goal: str) -> OutcomeContract:
        goal_lower = goal.lower()
        if any(w in goal_lower for w in ["learn", "study", "curriculum", "course"]):
            return OutcomeContract(
                objective=goal,
                success_criteria=["Comprehensive learning roadmap produced", "Curated resource list identified", "Study schedule outlined"],
                required_deliverables=["Learning roadmap and curriculum", "Curated resource list", "Study schedule"],
                required_evidence=["Course and documentation sources"],
                constraints=[],
                needs_external_research=True,
            )
        elif any(w in goal_lower for w in ["career", "job", "interview", "promotion", "senior"]):
            return OutcomeContract(
                objective=goal,
                success_criteria=["Career development plan produced", "Skill gap analysis completed"],
                required_deliverables=["Career development plan", "Skill gap analysis"],
                required_evidence=["Industry benchmarks"],
                constraints=[],
                needs_external_research=True,
            )
        elif any(w in goal_lower for w in ["budget", "finance", "save", "house", "down payment"]):
            return OutcomeContract(
                objective=goal,
                success_criteria=["Monthly budget created", "Savings timeline established"],
                required_deliverables=["Budget spreadsheet", "Savings strategy plan"],
                required_evidence=["Financial projections"],
                constraints=[],
                needs_external_research=False,
            )
        elif any(w in goal_lower for w in ["rich", "wealth", "money"]):
            return OutcomeContract(
                objective=goal,
                success_criteria=["Feasibility analysis completed", "Actionable wealth strategy outlined"],
                required_deliverables=["Wealth strategy roadmap", "Feasibility and risk analysis"],
                required_evidence=["Market data"],
                constraints=[],
                needs_external_research=True,
            )
        # Phase 10: Travel/visual/recommendation goals
        elif any(w in goal_lower for w in ["travel", "island", "beach", "vacation", "trip",
                                            "visit", "recommend", "photo", "picture",
                                            "destination", "visual", "illustration"]):
            return OutcomeContract(
                objective=goal,
                success_criteria=["Research-based recommendations produced", "Written travel/recommendation guide completed", "Inspiring visual imagery generated"],
                required_deliverables=["Travel or recommendation guide document",
                                        "A hero inspiration image of a recommended destination",
                                        "Research summary with cited sources"],
                required_evidence=["Travel reviews and ratings", "Destination information", "Photography references"],
                constraints=["Use reputable travel sources"],
                needs_external_research=True,
            )
        else:
            data = dict(DEFAULT_CONTRACT)
            data["objective"] = goal
            return OutcomeContract(**data)