"""Outcome Contract — formal definition of mission success (ADR-053).

Generated by LLM at mission start, validated by Pydantic, consumed by:
- WorkflowCompiler (decides what to plan)
- PlanCritic (validates plan covers contract)
- SemanticVerifier (checks deliverables against success criteria)
- MissionSupervisor (decides when mission is actually done)

Contract generation failures degrade gracefully: a minimal default contract
is always produced so the mission never hard-fails at this stage.
"""
import json
import os
import re
from datetime import datetime
from typing import Any, Dict, List, Optional

import httpx
from pydantic import BaseModel, Field

from packages.core.models import MissionIntent, utcnow


class OutcomeContract(BaseModel):
    objective: str
    success_criteria: List[str] = []
    required_deliverables: List[str] = []
    required_evidence: List[str] = []
    constraints: List[str] = []
    deadline: Optional[datetime] = None
    approval_policy: str = "default"   # default | strict | autonomous
    needs_external_research: bool = False

    def to_human_summary(self) -> str:
        lines = [f"Objective: {self.objective}"]
        if self.required_deliverables:
            lines.append("Deliverables:")
            lines.extend(f"  • {d}" for d in self.required_deliverables)
        if self.required_evidence:
            lines.append("Required evidence:")
            lines.extend(f"  • {e}" for e in self.required_evidence)
        if self.constraints:
            lines.append("Constraints:")
            lines.extend(f"  • {c}" for c in self.constraints)
        return "\n".join(lines)


CONTRACT_PROMPT = """You are NEXORA's Outcome Contract generator.
Given a user goal, produce a JSON contract that formally defines what success looks like.

USER GOAL:
{goal}

Return ONLY valid JSON matching this schema:
{{
  "objective": "one sentence restatement of the goal",
  "success_criteria": ["list of verifiable conditions for success"],
  "required_deliverables": ["concrete artifacts/documents/outputs to produce"],
  "required_evidence": ["information or sources needed to produce the deliverables"],
  "constraints": ["boundaries, prohibitions, or requirements"],
  "needs_external_research": true|false
}}

Rules:
- Be concrete, not vague.
- Deliverables should be specific (e.g. "financial model spreadsheet" not "financial analysis").
- If the goal requires information outside the user's own files (market data, competitors, external facts), set needs_external_research to true.
- Do NOT include tool names (no "google docs", no "veo"). Describe outcomes, not tools.
- Keep it concise: 3-8 deliverables, 3-6 success criteria, 2-5 evidence items.
"""


DEFAULT_CONTRACT = {
    "objective": "Execute the requested goal.",
    "success_criteria": ["The requested work is completed."],
    "required_deliverables": ["Summary of completed work"],
    "required_evidence": [],
    "constraints": ["No external communication without approval"],
    "needs_external_research": False,
}


class ContractGenerator:
    """LLM-based contract generator with deterministic fallback."""

    def __init__(self, api_key: Optional[str] = None, model: Optional[str] = None,
                 call_fn=None):
        self.api_key = api_key if api_key is not None else os.getenv("GEMINI_API_KEY", "")
        self.model = model or os.getenv("NEXORA_MODEL_T2", "gemini-2.0-flash")
        self.call_fn = call_fn   # test seam

    async def generate(self, goal: str, intent: Optional[MissionIntent] = None) -> OutcomeContract:
        if not self.api_key and not self.call_fn:
            return self._minimal_contract(goal)

        try:
            text = await self._call(self._prompt(goal))
            parsed = self._parse(text)
            if parsed is None:
                return self._minimal_contract(goal)
            return OutcomeContract(**parsed)
        except Exception as e:
            # Graceful degradation — never hard-fail a mission at contract stage
            return self._minimal_contract(goal)

    async def _call(self, prompt: str) -> str:
        if self.call_fn:
            return self.call_fn(prompt)
        url = f"https://generativelanguage.googleapis.com/v1beta/models/{self.model}:generateContent"
        async with httpx.AsyncClient(timeout=20) as c:
            r = await c.post(url, headers={"x-goog-api-key": self.api_key},
                             json={"contents": [{"parts": [{"text": prompt}]}],
                                   "generationConfig": {"temperature": 0.2}})
            r.raise_for_status()
            return r.json()["candidates"][0]["content"]["parts"][0]["text"]

    def _prompt(self, goal: str) -> str:
        return CONTRACT_PROMPT.format(goal=goal)

    def _parse(self, text: str) -> Optional[Dict[str, Any]]:
        m = re.search(r"\{.*\}", text, re.S)
        if not m:
            return None
        try:
            return json.loads(m.group(0))
        except Exception:
            return None

    def _minimal_contract(self, goal: str) -> OutcomeContract:
        data = dict(DEFAULT_CONTRACT)
        data["objective"] = goal
        return OutcomeContract(**data)